In [4]:
import numpy as np
import pandas as pd

In [2]:
list1 = np.array([1,2,3])
list2 = np.array([4,5,6])

list1*list2

array([ 4, 10, 18])

In [8]:
print(np.__version__)
print(pd.__version__)

2.1.2
2.2.3


In [10]:
print(list1.shape)
print(list1.dtype)
print(type(list1))
print(list1.ndim)

(3,)
int64
<class 'numpy.ndarray'>
1


In [15]:
list3 = np.array([[[0,1],[1,2]],[[3,4],[5,6]]])
print(list3)
print(list3.ndim)

[[[0 1]
  [1 2]]

 [[3 4]
  [5 6]]]
3


### Reshaping in np

In [21]:
array_2d = np.array([(1,2,3,4),(4,5,6,7)])
print(array_2d.reshape(4,-1))

[[1 2]
 [3 4]
 [4 5]
 [6 7]]


In [22]:
array_2d.flatten()

array([1, 2, 3, 4, 4, 5, 6, 7])

In [24]:
array_2d.tolist()

[[1, 2, 3, 4], [4, 5, 6, 7]]

In [31]:
array_2d.max(1)

array([4, 7])

In [39]:
array_2d.std(1)

array([1.11803399, 1.11803399])

In [41]:
array_2d.size

8